### ISSUE TITLE
png2frg source code?

### ISSUE THREAD

**Issue by zvezdochiot** [sisong/libfrg#21]
Subj.

**Comment by sisong** [comment]
png2frg source code is in another larger project, and the project is not open source;   
The frg format and other image format conversion mainly depends on this pixel array struct:
```
{    byte * pB8G8R8A8Color;
     int width;
     int height;
     int byte_width; }
```

**Comment by zvezdochiot** [comment]
@sisong say:
>png2frg source code is in another larger project, and the project is not open source;

What prevents to open exactly png2frg code?

**Comment by sisong** [comment]
coding time only;   
rewrite this app (png2frg) need: import libpng for encode&decode png data,  file read&write ,  cmdline txt dispose , makeFile , cross-platform compile, etc...     
maybe need write 1k line source code;  （ now png2frg app writed 200 line code by depend another existing project）

**Comment by zvezdochiot** [comment]
@sisong say:
>now png2frg app writed 200 line code by depend another existing project

In my opinion - initially a bad strategy. Maybe it's worth the time to get away from her?

**Comment by sisong** [comment]
added png2frg source code;   
used new libpng version,and only demo code,not need much code!

**Comment by zvezdochiot** [comment]
Good.
