### ISSUE TITLE
Bad calibration of quality

### ISSUE THREAD

**Issue by zvezdochiot** [sisong/libfrg#23]
libfrg 1.3.2:

On the test image `lena.png`
![lena.png](https://i111.fastpic.ru/big/2019/1215/8d/6060064bf82ded60d6f849c87bff4f8d.png)
at quality 50
```sh
png2frg lena.png lena.q50.frg 50
```
we get a bad image
![lena.q50.fgr](https://i111.fastpic.ru/big/2019/1215/71/29fc31fb6cd9da63dec7d9bbdfa22971.png)

I recommend recalibrating quality:
```
Qnew = (Q - 50) * 2    # 0 <- 50
```
or at least
```
Qnew = Q * Q /100    # 25 <- 50
```

**Comment by sisong** [comment]
try quality >=80

**Comment by zvezdochiot** [comment]
@sisong say:
>try quality >=80

I tried quality from 25 to 100 through 5.
The current scale is bad.
Changed to `qwork = sqrt (qin * 100) // Qn = Q * Q / 100`.
See https://github.com/Special-graphic-formats/libfrg/commit/25326f1d80d5d700d44fa58fcb7f39c44d6cd83b

**Comment by sisong** [comment]
we used frg image  in Games;    
default quality 80 mean "best";  try 75--50 to continue compress smaller for some tolerable images;
   
frg image quality 80：
![lena png frg80](https://user-images.githubusercontent.com/2347214/70862239-ad287a80-1f74-11ea-9cfd-b9b9050ca5dd.png)
test  png byte size  : 474756 
png decode time: 6.000 ms
frg byte size  : 272013 
frg decode time: 0.368 ms

**Comment by sisong** [comment]
your new calibration of quality is better for user;

**Comment by zvezdochiot** [comment]
@sisong say:
>default quality 80 mean "best"

You can apply the new calibration and set the default to 64 (== 80 old), if it is so important for you.

**Comment by sisong** [comment]
now calibration fit we(game images),you new calibration fit user(natural images)；
