### ISSUE TITLE
编码速度优化？

### ISSUE THREAD

**Issue by lulinfan** [sisong/libfrg#24]
FRG的解码速度确实挺快，但是编码速度非常慢，我在正常的PC上测试了下，编码一张1920*1080的bmp图片，大约耗时1-2秒之间，而对比JPEG压缩耗时在几十毫秒，有什么方法可以提升下编码的性能？例如增加内存占用或者其他的方式？
thanks

**Comment by zvezdochiot** [comment]
Hi @lulinfan .

Have you compared FRG encoding speed with [mozjpeg](https://github.com/mozilla/mozjpeg) or [bpg](https://bellard.org/bpg/)?

**Comment by sisong** [comment]
FRG产生的原因是在开发游戏的时候，觉得png和jpg加载都太慢，启动或切换场景都要等待好久；所以开发FRG时就主要考虑的是如何优化解压速度并尽量压得小一点。       
而压缩速度是比较慢，主要的时间应是花在了优化局部调色板和尝试一些针对文件大小的优化逻辑上。刚开发出来的时候更慢，后来进行了一些性能优化，估计现在可能的优化空间应该不太大。  我们只在发布游戏前用工具并行的将所有图片进行一次性转换；我们这边在实际应用中速度完全能够接受，速度略比压缩png慢一点；并且FRG对不同的图片压缩速度差异可能会很大。      
FRG不太适合于用在用户端压缩的场景。

**Comment by lulinfan** [comment]
> Hi @lulinfan .
> 
> Have you compared FRG encoding speed with [mozjpeg](https://github.com/mozilla/mozjpeg) or [bpg](https://bellard.org/bpg/)?

I am looking a format that have better quity than jpeg, and the decode speed faster than jpeg.  I can accept the compressed file size larger than JPEG 2-3 times.  so mojpeg and bpg is not my choice.

**Comment by lulinfan** [comment]
> FRG产生的原因是在开发游戏的时候，觉得png和jpg加载都太慢，启动或切换场景都要等待好久；所以开发FRG时就主要考虑的是如何优化解压速度并尽量压得小一点。
> 而压缩速度是比较慢，主要的时间应是花在了优化局部调色板和尝试一些针对文件大小的优化逻辑上。刚开发出来的时候更慢，后来进行了一些性能优化，估计现在可能的优化空间应该不太大。 我们只在发布游戏前用工具并行的将所有图片进行一次性转换；我们这边在实际应用中速度完全能够接受，速度略比压缩png慢一点；并且FRG对不同的图片压缩速度差异可能会很大。
> FRG不太适合于用在用户端压缩的场景。

确实不同的图像压缩速度差异挺大，我之前一般都是用一张Winodws截屏的图片来做测试，发现时间挺长。
目前耗时基本都是在createSubColorTable和createMatchs这两个函数里面。

如果可以接受压缩后文件再大一点，是否有减少压缩时间的可能性？

**Comment by sisong** [comment]
> 如果可以接受压缩后文件再大一点，是否有减少压缩时间的可能性？   

当然可行，你可以自己试着自己改改。

**Comment by lulinfan** [comment]
@sisong 有一些理论建议吗，我不确定小幅度的修改能够提升到一个什么样的水平。

**Comment by sisong** [comment]
这些修改可以加快几倍速度吧，但代价是文件变大，你可以试试看：   
1. `deleteColor(colorSet,maxTableSize,m_errorParameter);`     
这行可以删除，从而避免过慢的调色板缩减；当然你也可以用一个更快的调色板缩减算法替换；    
1. `TColorTableZiper::getColorSet` 可以优化，主要时间消耗在map表的内存申请和释放上了；      
1. `TInt tableMatchIndex=tableMatcher.findMatch(sub_table,&matchTableBit);`    
不需要相同调色板表匹配优化时，这行可以修改为：   
`TInt tableMatchIndex=-1;//tableMatcher.findMatch(sub_table,&matchTableBit);`    
1. `TColorMatch colorMatcher(m_srcRef,matchColorMask);`      
不需要相同像素块匹配优化时，这行可以修改为：   
`return; TColorMatch colorMatcher(m_srcRef,matchColorMask);`
